### ISSUE TITLE
feature request  add  update ini support failsafe 3 and 4 image format

### ISSUE THREAD

**Issue by armgong** [BeTeP-STH/mft-scripts#1]
Today I want mod a failsafe 4 image  confiugre INI file , but it said 
".bin is not supported FS2 image file", could you add failsafe 3 and 4 image support ?

**Comment by BeTeP-STH** [comment]
I do not have any compatible hardware. Also FS3 and FS4 are not some incremental improvements over FS2 - these are completely different.
